esphome:
  name: bmp-280-node2

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "27d616f4e9cb662be4b8b5822253d3cf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bmp-280-Node2 Fallback Hotspot"
    password: "j0RXUwayxedC"

i2c:
  sda: D2
  scl: D1
  scan: True

sensor:
  - platform: bmp280
    temperature:
      name: "Inside Temperature"
      oversampling: 16x
    pressure:
      name: "Inside Pressure"
    address: 0x76
    update_interval: 60s
    