esphome:
  name: smart-power-meter

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "fe309f839bb124ca03febf5d8c591d82"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart-Power-Meter"
    password: "QIkEbM79FzXd"

sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    name: "Measured Current"
    update_interval: 5s        #You may change this value (in seconds)
    id: measured_current       #Measured in ampere (I)
    filters:
    - calibrate_linear:
          - 0 -> 0
          - 0.00807 -> 1.2228

  # Example source sensor
  - platform: adc
    pin: A0
    id: adc_sensor
    
  - platform: total_daily_energy
    name: "Total Daily Power Usage"
    power_id: my_power

  - platform: template
    id: my_power
    name: "Measured Power"
    lambda: return id(measured_current).state * 120 / 1000; #Power = V*I/1000. So change 230V to whatever your mains voltage is)
    unit_of_measurement: 'kW'
    update_interval: 5s        #You may change this value (in seconds)

time:
  - platform: sntp
    id: my_time